/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ExampleComponent {
        "exampleProp": string;
        "exampleToUpperCase": () => Promise<void>;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface PriceTable {
        "detailone": string;
        "detailoneone": string;
        "detailonethree": string;
        "detailonetwo": string;
        "detailthree": string;
        "detailthreeone": string;
        "detailthreethree": string;
        "detailthreetwo": string;
        "detailtwo": string;
        "detailtwoone": string;
        "detailtwothree": string;
        "detailtwotwo": string;
        "product": string;
        "productthree": string;
        "producttwo": string;
    }
    interface QrGenerator {
        "link": string;
    }
}
declare global {
    interface HTMLExampleComponentElement extends Components.ExampleComponent, HTMLStencilElement {
    }
    var HTMLExampleComponentElement: {
        prototype: HTMLExampleComponentElement;
        new (): HTMLExampleComponentElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLPriceTableElement extends Components.PriceTable, HTMLStencilElement {
    }
    var HTMLPriceTableElement: {
        prototype: HTMLPriceTableElement;
        new (): HTMLPriceTableElement;
    };
    interface HTMLQrGeneratorElement extends Components.QrGenerator, HTMLStencilElement {
    }
    var HTMLQrGeneratorElement: {
        prototype: HTMLQrGeneratorElement;
        new (): HTMLQrGeneratorElement;
    };
    interface HTMLElementTagNameMap {
        "example-component": HTMLExampleComponentElement;
        "my-component": HTMLMyComponentElement;
        "price-table": HTMLPriceTableElement;
        "qr-generator": HTMLQrGeneratorElement;
    }
}
declare namespace LocalJSX {
    interface ExampleComponent {
        "exampleProp"?: string;
        "onExampleEvent"?: (event: CustomEvent<string>) => void;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface PriceTable {
        "detailone"?: string;
        "detailoneone"?: string;
        "detailonethree"?: string;
        "detailonetwo"?: string;
        "detailthree"?: string;
        "detailthreeone"?: string;
        "detailthreethree"?: string;
        "detailthreetwo"?: string;
        "detailtwo"?: string;
        "detailtwoone"?: string;
        "detailtwothree"?: string;
        "detailtwotwo"?: string;
        "product"?: string;
        "productthree"?: string;
        "producttwo"?: string;
    }
    interface QrGenerator {
        "link"?: string;
    }
    interface IntrinsicElements {
        "example-component": ExampleComponent;
        "my-component": MyComponent;
        "price-table": PriceTable;
        "qr-generator": QrGenerator;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "example-component": LocalJSX.ExampleComponent & JSXBase.HTMLAttributes<HTMLExampleComponentElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "price-table": LocalJSX.PriceTable & JSXBase.HTMLAttributes<HTMLPriceTableElement>;
            "qr-generator": LocalJSX.QrGenerator & JSXBase.HTMLAttributes<HTMLQrGeneratorElement>;
        }
    }
}
